AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront for Static website hosting

Parameters:
  BucketName:
    Type: String

  DomainName:
    Type: String

  CFSSLCertificateId:
    Type: String
    
  BucketDomainName:
    Type: String

  CloudFrontOriginAccessIdentity:
    Type: String

  # MyWebACL:
  #   Type: String

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_All
        Aliases:
          - !Ref DomainName
        Origins:
          - DomainName: !Ref BucketDomainName
            Id: !Sub "S3origin-${BucketName}"
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        Logging:
          IncludeCookies: "true"
          Bucket: !Sub "${BucketName}-log.s3.amazonaws.com"
          Prefix: frontend/cloudfront
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Sub "S3origin-${BucketName}"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          DefaultTTL: 3600
          MaxTTL: 86400
          MinTTL: 60
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: false
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
          AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CFSSLCertificateId}"
        HttpVersion: http2
        Enabled: true
        CustomErrorResponses:
          - ResponsePagePath: /
            ErrorCode: 403
            ResponseCode: 200
          - ResponsePagePath: /
            ErrorCode: 404
            ResponseCode: 404
        # WebACLId: !Ref MyWebACL

Outputs:
  DistributionID:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${BucketName}-CloudFrontDistribution

  DomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${BucketName}-CloudFrontDomainName
