AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for SPA Web Application

Parameters:
  BucketName:
    Type: String

Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName

  LogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${BucketName}-log"

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "access-identity-${Bucket}"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

Outputs:
  BucketName:
    Value: !Ref Bucket
    Export:
      Name: !Sub ${BucketName}-Bucket

  CloudFrontOriginAccessIdentity:
    Value: !Ref CloudFrontOriginAccessIdentity
    Export:
      Name: !Sub ${BucketName}-CloudFrontOriginAccessIdentity

  BucketDomainName:
    Value: !GetAtt Bucket.DomainName
    Export:
      Name: !Sub ${BucketName}-DomainName
